name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build
      run: npm run build
      
    - name: Fix MIME types
      run: |
        echo "Setting up MIME type fixes..."
        cd dist
        # Create .nojekyll file
        touch .nojekyll
        # Create custom headers for GitHub Pages
        echo "Content-Type: application/javascript; charset=utf-8" > .htaccess
        echo "AddType application/javascript .js" >> .htaccess
        echo "AddType text/css .css" >> .htaccess
        echo "AddType text/html .html" >> .htaccess
        ls -la
        
    - name: Setup Pages
      uses: actions/configure-pages@v4
      
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: './dist'
        
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
